<?php

namespace VRL\AdminBundle\Repository;

/**
 * aboutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class aboutRepository extends \Doctrine\ORM\EntityRepository
{
}
