<?php

namespace VRL\AdminBundle\Repository;

/**
 * catsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class catsRepository extends \Doctrine\ORM\EntityRepository
{
}
