<?php

namespace VRL\AdminBundle\Repository;

/**
 * paragrapheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class paragrapheRepository extends \Doctrine\ORM\EntityRepository
{
}
