<?php

namespace VRL\AdminBundle\Repository;

/**
 * posteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class posteRepository extends \Doctrine\ORM\EntityRepository
{
}
