<?php

namespace VRL\AdminBundle\Repository;

/**
 * websiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class websiteRepository extends \Doctrine\ORM\EntityRepository
{
}
